spring.application.name=protocolo-zero
spring.datasource.url=jdbc:postgresql://localhost:5432/protocolozerodb
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:password123}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true